alarm/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^users/all/', views.list_users, name='all_users'),
    url(r'^users/get/', views.get_user, name='get_user'),
    url(r'^users/add/', views.add_user, name='add_user'),
    url(r'^users/update/', views.update_user, name='update_user'),
    url(r'^users/delete/', views.delete_user, name='delete_user'),
    url(r'^users/', views.users_view, name='users'),
    url(r'^logs/get/today/', views.get_logs_today, name='today_logs'),
    url(r'^logs/get', views.get_logs_date, name='date_logs'),
    url(r'^logs/', views.logs_view, name='logs'),
    url(r'^config/status/get/', views.get_config_status, name='alarm_status_get'),
    url(r'^config/status/update/', views.update_alarm_status, name='alarm_status_update'),
    url(r'^alerts/latest/', views.get_alerts_status, name='alerts_latest_status'),
    url(r'^alerts/', views.alerts_view, name='alerts'),
    url(r'^$', views.index_view, name='dashboard'),
]

alarm_service/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from alarm import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^authenticate/', include('authentication.urls', namespace="authenticate")),
    url(r'^alarm/', include('alarm.urls', namespace="alarm")),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api/', include('api.urls', namespace="api")),
    url(r'^$', views.index_view, name="alarm"),
]

api/urls.py
from django.conf.urls import url, include
from rest_framework import routers
from views import UserProfileViewSet, LogViewSet, AlertViewSet, AlarmStateConfigurationSet


""" Routers provide an easy way of automatically determining the URL conf. """


router = routers.DefaultRouter()
router.register(r'users', UserProfileViewSet)
router.register(r'logs', LogViewSet)
router.register(r'alerts', AlertViewSet)
router.register(r'configuration', AlarmStateConfigurationSet)

urlpatterns = [
    url(r'^', include(router.urls)),
]

alarm/models.py
from __future__ import unicode_literals

from django.conf import settings
from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver
from rest_framework.authtoken.models import Token
from alerts import SMSAlert
from django.utils import timezone

from django.db import models

"""Alarm models"""

DOOR_STATUS = (
    ('0', 'open'),
    ('1', 'closed'),
)

ALARM_STATUS = (
    ('0', 'off'),
    ('1', 'on'),
)

CLIENT_STATUS = (
    ('0', 'disconnected'),
    ('1', 'connected'),
)


class AlarmStateConfiguration(models.Model):

    alarm_name = models.CharField(
        primary_key=True,
        max_length=20,
        null=False,
        default='primary'
    )
    alarm_status = models.CharField(
        max_length=1,
        choices=ALARM_STATUS
    )
    last_notified_time = models.DateTimeField(
        null=True,
        blank=True
    )
    client_connected_state = models.CharField(
        max_length=1,
        choices=CLIENT_STATUS
    )
    last_client_connected_time = models.DateTimeField(
        null=True,
        blank=True
    )
    alarm_message = models.TextField(
        null=False,
        blank=False
    )

    def publish(self):
        self.save()

    def __str__(self):
        return self.alarm_name


class Alert(models.Model):

    type = models.CharField(
        max_length=10,
        null=False,
        default='SMS'
    )
    sent = models.PositiveIntegerField(
        verbose_name='messages sent',
        default=0
    )
    remaining = models.PositiveIntegerField(
        verbose_name='messages remaining',
        default=0
    )
    message_id = models.CharField(
        verbose_name='message ID',
        max_length=200,
        null=True,
        blank=True,
    )
    time = models.DateTimeField()

    class Meta:
        get_latest_by = "time"

    def publish(self):
        self.time = timezone.now()
        self.save()

    def __str__(self):
        return "{} - {}".format(
            self.type, self.time
        )


class Log(models.Model):
    time_stamp = models.DateTimeField()
    door_state = models.CharField(
        max_length=1,
        choices=DOOR_STATUS
    )
    alarm_state = models.CharField(
        max_length=1,
        choices=ALARM_STATUS,
        blank=True
    )
    client_state = models.CharField(
        max_length=1,
        choices=CLIENT_STATUS,
        blank=True
    )

    def publish(self):
        self.save()

    def __str__(self):
        return self.time_stamp.strftime(
            settings.DATE_TIME_FORMAT
        )


class UserProfile(models.Model):
    name = models.CharField(
        max_length=200,
        null=False,
        blank=False
    )
    email = models.CharField(
        max_length=200,
        null=False,
        blank=False
    )
    mobile = models.CharField(
        max_length=200,
        null=False,
        blank=False
    )

    def publish(self):
        self.save()

    def __str__(self):
        return self.name


def _log_alert(response):

    sent = 1

    if Alert.objects.all():
        last_alert = Alert.objects.latest()
        sent = last_alert.sent + 1

    text_id = 0
    remaining = 0

    if response['success']:
        text_id = response['textId']
        remaining = response['quotaRemaining']

    new_alert = Alert(type='SMS',
                      sent=sent,
                      remaining=remaining,
                      message_id=text_id,
                      )

    new_alert.publish()


def send_alerts_to_users(alarm_state, client_state):
    if alarm_state == '1' or client_state == '0':
        alert = SMSAlert()
        users = UserProfile.objects.all()
        for user in users:
            response = alert.send_alert(AlarmStateConfiguration.objects.get(
                alarm_name=settings.ALARM_NAME).alarm_message, user.mobile)
            _log_alert(response)


@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)


@receiver(pre_save, sender=Log)
def set_alarm_states(sender, instance, *args, **kwargs):
    instance.alarm_state = AlarmStateConfiguration.objects.get(
                                alarm_name=settings.ALARM_NAME).alarm_status

    instance.client_state = AlarmStateConfiguration.objects.get(
                                alarm_name=settings.ALARM_NAME).client_connected_state


@receiver(post_save, sender=Log)
def send_alerts(sender, instance=None, created=False, **kwargs):
    send_alerts_to_users(instance.alarm_state, instance.client_state)

alarm/forms.py
from django import forms
from models import UserProfile, AlarmStateConfiguration


class UserProfileForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)

    class Meta:
        model = UserProfile
        fields = ('name', 'email', 'mobile')


class AlarmStateConfigurationForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(AlarmStateConfigurationForm, self).__init__(*args, **kwargs)

    class Meta:
        model = AlarmStateConfiguration
        fields = ('alarm_name', 'alarm_status', 'client_connected_state')

alarm/views.py
import json
import datetime
from django.http import HttpResponse
from django.core import serializers
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404

from alarm.forms import UserProfileForm, AlarmStateConfigurationForm
from alarm.models import UserProfile, Log, Alert, AlarmStateConfiguration


"""Views"""

SUCCESS_RESPONSE = {'success': True}


# Index render view
@login_required
def index_view(request):
    return render(request, "alarm/index.html")


@login_required
def logs_view(request):
    return render(request, "alarm/logs.html")


@login_required
def users_view(request):
    return render(request, "alarm/users.html")


@login_required
def alerts_view(request):
    return render(request, "alarm/alerts.html")


@login_required
def list_users(request):
    if request.is_ajax:
        users = UserProfile.objects.all()
        data = serializers.serialize("json", users)
        return HttpResponse(data,
                            content_type='application/json')


@login_required
def get_user(request):
    if request.is_ajax:
        user = UserProfile.objects.get(pk=request.GET['id'])
    data = serializers.serialize("json", [user])
    return HttpResponse(data,
                        content_type='application/json')


@login_required
def add_user(request):
    if request.method == 'POST':
        form = UserProfileForm(request.POST)
        form.save()
        return HttpResponse(json.dumps(SUCCESS_RESPONSE),
                            content_type='application/json')


@login_required
def update_user(request):
    if request.method == 'POST':
        user = get_object_or_404(UserProfile, id=request.POST['id'])
        form = UserProfileForm(request.POST or None, instance=user)
        if form.is_valid():
            form.save()
            return HttpResponse(json.dumps(SUCCESS_RESPONSE), content_type='application/json')


@login_required
def delete_user(request):
    if request.method == 'POST':
        user = UserProfile.objects.get(pk=request.POST['id'])
        user.delete()
        return HttpResponse(json.dumps(SUCCESS_RESPONSE), content_type='application/json')


@login_required
def get_logs_today(request):
    if request.is_ajax:
        logs = Log.objects.filter(time_stamp__date=datetime.date.today())
        data = serializers.serialize("json", logs)
        return HttpResponse(data,
                            content_type='application/json')


@login_required
def get_logs_date(request):
    if request.is_ajax:
        logs = Log.objects.filter(time_stamp__date=request.GET['date'])
        data = serializers.serialize("json", logs)
        return HttpResponse(data,
                            content_type='application/json')


@login_required
def get_config_status(request):
    if request.is_ajax:
        config = AlarmStateConfiguration.objects.filter(alarm_name=settings.ALARM_NAME)
        data = serializers.serialize("json", config)
        return HttpResponse(data,
                            content_type='application/json')


@login_required
def update_alarm_status(request):
    if request.method == 'POST':
        alarm = get_object_or_404(AlarmStateConfiguration, alarm_name=request.POST['alarm_name'])
        form = AlarmStateConfigurationForm(request.POST or None, instance=alarm)
        if form.is_valid():
            form.save()
            return HttpResponse(json.dumps(SUCCESS_RESPONSE), content_type='application/json')


@login_required
def get_alerts_status(request):
    if request.is_ajax:
        if Alert.objects.all():
            alerts = Alert.objects.latest()
            data = serializers.serialize("json", [alerts])
        else:
            data = serializers.serialize("json", [])
        return HttpResponse(data,
                            content_type='application/json')

alarm/templates/alarm/alerts.html
{% extends "alarm/layout.html" %}

{% block heading %}

  <div>
    <br/>
    <h2><i class="fa fa-exclamation-triangle fa-fw" aria-hidden="true"></i> Alerts</h2>
  </div>

{% endblock %}

{% block body %}

  <br/>

  <div id="alerts-empty" class="alert alert-info" role="alert" hidden>
      <i class="fa fa-info fa-fw" aria-hidden="true"></i>
      No alerts status to display
  </div>

  <div id="alerts-error" class="alert alert-danger" role="alert" hidden>
      <i class="fa fa-exclamation-circle fa-fw" aria-hidden="true"></i>
      <span id="error-msg">Error:</span>
  </div>

  <div class="well">

      <table class="table table-striped table-hover" id="alerts">
      <thead>
        <tr>
          <th>Last sent</th>
          <th>Type</th>
          <th>Sent</th>
          <th>Remaining</th>
        </tr>
      </thead>
      <tbody>

      </tbody>
    </table>

  </div>

{% endblock %}

{% block jsfiles %}

{% load staticfiles %}
<script src="{% static 'resources/js/alarm.js' %}"></script>
<script src="{% static 'resources/js/alarm-alerts.js' %}"></script>

{% endblock %}

alarm/templates/alarm/index.html
{% extends "alarm/layout.html" %}

{% block heading %}

  <div>
    <br/>
    <h2><i class="fa fa-dashboard fa-fw" aria-hidden="true"></i> Alarm system dashboard</h2>
  </div>

{% endblock %}

{% block body %}

  <div class="container">
      <div class="row">
          <div class="col-md-11">
              <div id="client-disconnected-alert" class="alert alert-danger" role="alert" hidden>
                <i class="fa fa-exclamation-circle fa-fw" aria-hidden="true"></i>
                Client is disconnected
              </div>
          </div>
          <div class="col-md-1">
              <input id="alarm-switch" name="primary" type="checkbox" data-toggle="toggle"
                     data-size="large" data-on="On" data-off="Off" data-onstyle="danger" data-offstyle="info">
              <input id="client-state" name="" hidden>
          </div>
      </div>
      <hr/>

      <div class="jumbotron">
        <div class="container">
          <p>Alarm System Dashboard</p>
        </div>
      </div>

      <h3><i class="fa fa-file fa-fw" aria-hidden="true"></i> Today's activity logs</h3>

      <hr/>

      <div class="well">

          <table class="table table-striped table-hover" id="logs-list">
              <thead>
                <tr>
                  <th>Date/time</th>
                  <th>Door state</th>
                  <th>Alarm state</th>
                  <th>Client state</th>
                </tr>
              </thead>
              <tbody>

              </tbody>
          </table>

      </div>

  </div>

{% endblock %}

{% block jsfiles %}

{% load staticfiles %}
<script src="{% static 'resources/js/alarm.js' %}"></script>
<script src="{% static 'resources/js/alarm-logs.js' %}"></script>
<script src="{% static 'resources/js/alarm-dashboard.js' %}"></script>

{% endblock %}

alarm/templates/alarm/layout.html
<!DOCTYPE html>
<html class="no-js" lang="en" dir="ltr">
<head>

    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Alarm</title>
    {% load static from staticfiles %}
    <link href="{% static 'resources/css/Bootstrap-3.3.6/bootstrap.min.css' %}" rel="stylesheet"/>
    <link href="{% static 'resources/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet"/>
    <link href="{% static 'resources/css/datatables.min.css' %}" rel="stylesheet"/>
    <link href="{% static 'resources/css/select2.min.css' %}" rel="stylesheet"/>
    <link href="{% static 'resources/css/Bootstrap-3.3.6/bootstrap-datepicker.css' %}" rel="stylesheet"/>
    <link href="{% static 'resources/css/Bootstrap-3.3.6/bootstrap-toggle.min.css' %}" rel="stylesheet"/>
    <link href="{% static 'resources/fancybox/jquery.fancybox.css' %}" rel="stylesheet"/>
    <link href="{% static 'resources/css/sticky-footer.css' %}" rel="stylesheet"/>
</head>
<body>

    <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{%url 'alarm:dashboard' %}"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="navbar-collapse">
        <ul class="nav navbar-nav">
          <li><a href="{%url 'alarm:logs' %}"><i class="fa fa-file fa-fw"></i> Logs</a></li>
          <li><a href="{%url 'alarm:alerts' %}"><i class="fa fa-exclamation-triangle fa-fw"></i> Alerts</a></li>
          <li><a href="{%url 'alarm:users' %}"><i class="fa fa-users fa-fw"></i> Users</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><a href="/authenticate/logout/"><i class="fa fa-sign-out fa-fw"></i> Logout</a></li>
        </ul>

      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
    </nav>

    <div class="container">

      {% block heading %} {% endblock %}

    </div>

    <hr/>
    <br/>

    <div class="container">

      {% block body %} {% endblock %}

    </div>

    <br/>

    <footer class="footer">
      <div class="footer-container" align="center">
        <p class="text-muted">
            <b>Author: Silvian Dragan</b>
            <i>© Copyright 2017, Alarm, Licence: GPL v3</i>
        </p>
      </div>
    </footer>

    {% load staticfiles %}
    <script src="{% static 'resources/js/jquery.min.js' %}"></script>
    <script src="{% static 'resources/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'resources/js/bootstrap-datepicker.js' %}"></script>
    <script src="{% static 'resources/js/bootstrap-toggle.min.js' %}"></script>
    <script src="{% static 'resources/js/datatables.min.js' %}"></script>
    <script src="{% static 'resources/js/select2.min.js' %}"></script>
    <script src="{% static 'resources/js/blockui.js' %}"></script>
    <script src="{% static 'resources/js/moments.min.js' %}"></script>
    <script src="{% static 'resources/fancybox/jquery.fancybox.js' %}"></script>
    {% block jsfiles %} {% endblock %}

</body>
</html>

alarm/templates/alarm/login.html
{% extends "alarm/layout.html" %}

{% block heading %}

<div>
  </br>
  <h2><i class="fa fa-user fa-fw" aria-hidden="true"></i> Login</h2>
</div>

{% endblock %}

{% block body %}

{% if logout %}
    <div class="alert alert-info" role="alert">
      <i class="fa fa-check fa-fw" aria-hidden="true"></i>
      {{ msg }}
    </div>

{% elif msg %}
    <div class="alert alert-danger" role="alert">
      <i class="fa fa-exclamation-circle fa-fw" aria-hidden="true"></i>
      <span class="sr-only">Error:</span>
      {{ msg }}
    </div>
{% endif %}

<h4>Enter username and password</h4>

<div class="col-md-4 well">
    <form role="form" enctype="multipart/form-data" action="/authenticate/access/" method="post">
        {% csrf_token %}
        <fieldset class="form-group">
            <input class="form-control" type="text" id="username" name="username" placeholder="username" required autofocus>
        </fieldset>
        <fieldset class="form-group">
            <input class="form-control" type="password" id="password" name="password" placeholder="password" required>
        </fieldset>
        <button class="btn btn-primary" type = "submit" name = "login"><i class="fa fa-sign-in fa-fw"></i> Login</button>

    </form>
</div>

{% endblock %}

alarm/templates/alarm/logs.html
{% extends "alarm/layout.html" %}

{% block heading %}

  <div>
    <br/>
    <h2><i class="fa fa-file fa-fw" aria-hidden="true"></i> Alarm system logs</h2>
  </div>

{% endblock %}

{% block body %}

  <div class="container">
    <button type="button" class="btn btn-primary btn-md" id="select-date" data-date-format="dd-mm-yyyy">
        <i class="fa fa-calendar fa-fw"></i> Log date
    </button>

  </div>

  <br/>

  <div class="well">

      <table class="table table-striped table-hover" id="logs-list">
      <thead>
        <tr>
          <th>Date/time</th>
          <th>Door state</th>
          <th>Alarm state</th>
          <th>Client state</th>
        </tr>
      </thead>
      <tbody>

      </tbody>
    </table>

  </div>

{% endblock %}

{% block jsfiles %}

{% load staticfiles %}
<script src="{% static 'resources/js/alarm.js' %}"></script>
<script src="{% static 'resources/js/alarm-logs.js' %}"></script>

{% endblock %}

alarm/templates/alarm/users.html
{% extends "alarm/layout.html" %}

{% block heading %}

  <div>
    <br/>
    <h2><i class="fa fa-users fa-fw" aria-hidden="true"></i> Users</h2>
  </div>

{% endblock %}

{% block body %}

  <div class="container">

    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary btn-md" style="float:right" id="add-user-button">
        <i class="fa fa-users fa-fw"></i> New User
    </button>

  </div>

  <br/>

  <div id="users-empty" class="alert alert-info" role="alert" hidden>
      <i class="fa fa-info fa-fw" aria-hidden="true"></i>
      No users have been created yet. Start by adding a new user.
  </div>

  <div id="users-error" class="alert alert-danger" role="alert" hidden>
      <i class="fa fa-exclamation-circle fa-fw" aria-hidden="true"></i>
      <span id="error-msg">Error:</span>
  </div>

  <div class="well">

      <table class="table table-striped table-hover" id="users-list">
      <thead>
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th>Mobile</th>
          <th>Remove</th>
        </tr>
      </thead>
      <tbody>

      </tbody>
    </table>

  </div>

{% include "alarm/modals/user_modal.html" %}

{% include "alarm/modals/delete_modal.html" %}

{% endblock %}

{% block jsfiles %}

{% load staticfiles %}
<script src="{% static 'resources/js/alarm.js' %}"></script>
<script src="{% static 'resources/js/alarm-users.js' %}"></script>

{% endblock %}